config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dogs do
    resources :walks, except: [:index]
  end

  resources :walks, only: [:index]

  get :mydogs, to: 'dogs#mydogs'

  resources :chats, only: [:index, :show, :create] do
    resources :messages, only: [:index, :create]
  end

  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
  class Chat < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) {
    where("chats.sender_id = ? OR chats.recipient_id = ?", user.id, user.id)
  }

  scope :between, -> (user_A, user_B) {
    where("(chats.sender_id = ? AND chats.recipient_id = ?) OR (chats.sender_id = ? AND chats.recipient_id = ?)", user_A, user_B, user_B, user_A)
  }

  # The scopes will allow us to call Chat.involving(current_user) to find the chats where the current_user is participating
  # and Chat.between(current_user, another_user) to find the chats between these two users.


  # Due to our validates_uniqueness_of there will only be one chat between any two users,
  #  but the between scope will still return an ActiveRecordCollection [array like object].
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :walks

  mount_uploader :picture, PhotoUploader


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates_presence_of :body, :chat_id, :user_id

  # Helper method to format the display time
  def message_time
    created_at.strftime("%d %b, %Y")
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs
  has_many :walks

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :picture, PhotoUploader

  def full_name
    "#{firstname} #{lastname}"
  end

  def sender?(conversation)
    self == conversation.sender
  end

  def recipient?(conversation)
    self == conversation.recipient
  end
end

app/models/walk.rb
class Walk < ApplicationRecord
  belongs_to :dog
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    #@chats = Chat.involving(current_user)
    @chats = policy_scope(Chat).order(created_at: :desc)
  end

  def show
    @chat = Chat.find(params[:id])
    authorize @chat
    @other_user = current_user == @chat.sender ? @chat.recipient : @chat.sender
    @messages = @chat.messages.order(created_at: :asc).last(20)
    @message = Message.new
  end

  def create
    duo = params[:duo]
    sender_id = duo[:sender_id]
    recipient_id = duo[:recipient_id]
    @chat = Chat.between(sender_id, recipient_id).first

    if !@chat
      @chat = Chat.create!(sender_id: sender_id, recipient_id: recipient_id)
    end
   # @chat = Chat.between(sender_id, recipient_id).first_or_create!(sender_id, recipient_id)

    authorize @chat
    redirect_to @chat
  end

  private

  def chat_params
    params.permit(:duo, :sender_id, :recipient_id)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :fetch_dog, except: [:index, :new, :create, :mydogs]

  def index
    @dogs = policy_scope(Dog).order(created_at: :desc)
    #  @flats = Flat.where.not(latitude: nil, longitude: nil)
    @markers = @dogs.map do |dog|
      {
        lat: dog.user.latitude,
        lng: dog.user.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
    @walk = Walk.new
    @marker = [
    {
      lat: @dog.user.latitude,
      lng: @dog.user.longitude#,
      # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
    }
    ]

  end

  def mydogs
    @dogs = Dog.where(user: current_user)
    authorize @dogs
  end

  def new
    @dog = Dog.new()
    authorize @dog
  end

  def create
    @dog = Dog.new(dog_params)
    authorize @dog
    @dog.user = current_user

    if @dog.save
      redirect_to dogs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @dog.update(dog_params)

    redirect_to dog_path
  end

  def destroy
    @dog.destroy
    redirect_to dogs_path
  end


  private

  def fetch_dog
    @dog = Dog.find(params[:id])
    authorize @dog
  end

  def dog_params
    params.require(:dog).permit(:name, :breed, :sex, :size, :bio, :age, :picture,:hourly_price)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chat

  def create
    @message = @chat.messages.new(message_params)
    @messages = @chat.messages.order(created_at: :desc)
    authorize @message
    if @message.save
      redirect_to chat_messages_path(@chat)
    end
  end

  private

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def message_params
    params.require(:message).permit(:body, :user_id, :chat_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :fetch_dog, except: [:index]
  before_action :fetch_walk, only: [:show,:edit]
  def index
    # Probablment a modifier avec le search
    #@walks = @
    @walks = policy_scope(Walk).order(created_at: :desc)
  end

  def show
    # work done by the before_action
  end

  def new
    @walk = Walk.new
    authorize @walk
  end

  def create
    @walk = Walk.new(walk_params)
    authorize @walk
    @walk.user = current_user
    @walk.dog = @dog

    if @walk.save
      redirect_to dog_walk_path(params[:dog_id], @walk)
    else
      redirect_to @dog
    end
  end

  private

  def fetch_dog
    @dog = Dog.find(params[:dog_id])
  end

  def fetch_walk
    @walk = Walk.find(params[:id])
    authorize @walk
  end

  def walk_params
    params.require(:walk).permit(:dogwalker_id, :dog_id, :date_begin, :date_end, :startime, :duration)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_chat.html.erb
<% other_user = current_user.sender?(chat) ? chat.recipient : chat.sender %>
<%= link_to chat do %>
  <div class="row chat">
    <% if chat.messages.any? %>
      <div class="col-md-4">
        <%= other_user.full_name %>
        <%= chat.messages.last.message_time %>
      </div>
      <div class="col-md-8">
        <%= chat.messages.last.body %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/chats/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Your Chats</div>
      <div class="panel-body">
        <div class="container">
          <% @chats.each do |chat|%>
            <%= render 'chat', chat: chat %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<div class="wrapper-chat container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">


        <div class="messages">
          <div class="messages-content">
            <% @messages.each do |message|%>
            <%= render "/messages/messages", message: message,
            user_is_messages_author: message.user == current_user %>
            <% end %>
          </div>
        </div>


        <div class="chat--form">
          <%= form_for [@chat, @message] do |f| %>
            <div class="message-form">
              <%= f.text_field :body, placeholder: "Type message", autofocus: true, class: "message-form--input" %>
              <%= f.hidden_field :chat_id, value: @chat.id %>
              <%= f.submit "Send", class: "message-form--submit" %>
            </div>
          <% end %>
        </div>


    </div>
  </div>
</div>

app/views/chats/showORIGINAL.html.erb
<div style="margin-top: 30px; height: calc(100vh - 130px);">
    <div class="chat container">
      <div class="messages">
        <div class="messages--content">
          <% @messages.each do |message|%>
          <%= render '/messages/messages', message: message %>
          <% end %>
        </div>
      </div>
      <div class="chat--form">
        <%= form_for [@chat, @message] do |f| %>
          <div class="message-form">
            <%= f.text_field :body, placeholder: "Type message", autofocus: true, class: "message-form--input" %>
            <%= f.hidden_field :chat_id, value: @chat.id %>
            <%= f.submit "Send", class: "message-form--submit" %>
          </div>
        <% end %>
      </div>
    </div>

</div>

app/views/dogs/_form.html.erb
<div class="form-box">
  <p>Add/Edit a Doggie</p>
<%= simple_form_for(@dog) do |f| %>
  <%= f.input :name %>
  <%= f.input :breed %>
  <%= f.input :bio %>
  <%= f.input :sex %>
  <%= f.input :age %>
  <%= f.input :hourly_price %>
  <%= f.input :picture %>
  <%= f.input :picture_cache, as: :hidden %>
  <%= f.submit "Submit", class: "btn btn-primary wide-button" %>
<% end %>

</div>

app/views/dogs/_formdate.html.erb
<%= simple_form_for [@dog, @walk] do |f| %>
<div class="dog-walk-table">
  <div class="dog-walk-form">
    <p>
  <%= f.input :date_begin, as: :string, id:"walk_date_begin", class:"flatpickr-input"  %>
    </p>
    <p>
  <%= f.input :date_end, as: :string, id:"walk_date_end", class:"flatpickr-input" %>
    </p>
  </div>


</div>

    <div class="dog-walk-box">
      <%= f.submit "Let's have a walk!",class: "btn btn-danger" %>
    </div>

<% end %>

app/views/dogs/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-offset-2 col-sm-8">
          <div class="dog-card">
              <%= render 'form', dog: @dog %>
            <%= link_to 'back to Dogs', dogs_path  %>
          </div>
      </div>
    </div>
</div>

app/views/dogs/index.html.erb
 <div class="content">
    <div class="cards-container" >
      <div class="row">
        <% @dogs.each do |dog| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path dog.picture, height: 300, width: 400, crop: :limit %> ');">
              <div class="card-category"> <%= dog.breed %></div>
              <div class="card-description">
                <h2><%= dog.name %></h2>
                <p>price / hour = <%= dog.hourly_price %></p>
              </div>
              <img class="card-user" src='<%= cl_image_path dog.user.picture,width: 150, height: 150, crop: :thumb, gravity: :face %>'>
              <!-- <a class="card-link" href= ></a> -->
              <%= link_to '', dog, class: "card-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div id="map" style="width: 100%;  height: 100vh;" data-markers="<%= @markers.to_json %>"></div>
  </div>

app/views/dogs/mydogs.html.erb
<% @dogs.each do |dog| %>
  <p> Dog's name : <%= dog.name %> </p>
  <p> Dog's breed: <%= dog.breed %></p>
<% end %>

app/views/dogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <div class="dog-card">
        <%= render 'form', dog: @dog %>
        <%= link_to 'back to Dogs', dogs_path  %>
      </div>
    </div>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="wrapper-dogshow">
  <div class="card-mapContainer">
    <div class="row">
      <div class="col-sm-4">
        <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path @dog.picture, height: 300, width: 450, crop: :fill %> ');">
        </div>
      </div>
      <div class="col-sm-8">
        <div id="map-show" style="width: 100%; height: 250px; "data-markers="<%= @marker.to_json %>"> </div>
      </div>
    </div>
  </div>

  <div class="wrapper-dog-info container">
    <div class="dog-left-show">
      <div class="dog-top-section">
        <div class="dog-details-name">
          <h1> I'm <%= @dog.name %>, nice to meet you</h1>
        </div>
        <div class="dog-breed-price">
          <div class="dog-details-breed">
            <%= @dog.breed %>
          </div>
          <div class="dog-details-price">
            <p><%= @dog.hourly_price %> euros/h </p>
          </div>
        </div>
      </div>
      <div class="dog-bottom-section">
        <div class="dog-bio">
          <p> <%= @dog.bio %> </p>
        </div>

        <% if policy(@dog).update? %>
          <%= link_to "Edit Dog Information", edit_dog_path(@dog), class:"btn btn-primary" %>
          <%= link_to "Remove my Dog", dog_path(@dog), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-warning" %>
        <% end %>
      </div>

      <%= link_to 'Do you want to chat with my Master?', chats_path(:duo => {:sender_id => @dog.user.id,
        :recipient_id =>  current_user.id}), method: :post, class: "btn btn-primary btn-lg"%>

    </div>
    <div class="dog-datepicker">
      <%= render 'formdate', walk: @walk %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> DogWalker </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/_messages.html.erb
<div class="message <%= user_is_messages_author ? "right" : "" %>">
  <div class="message--header">
    <span class="message--author">
      <%= message.user.firstname %>
    </span>
    <span class="message--time">
      <%= message.message_time %>
    </span>
  </div>
  <div class="message-content">
    <% message.body.lines.each do |line| %>
      <p><%= line %></p>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>
<div class="page-wrapper">
  <div class="banner">
    <div class="banner-content text-center">
      <h1>Let's walk your Dog</h1>
      <p>We bring Dogwalkers in contact with you</p>
      <%= link_to "Start now", new_user_session_path, class: "btn btn-lg btn-primary"  %>

<!--  EFFECT from PubCrawler but isn't working -->
<!--     <ul class="slideshow">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul> -->
    </div>
  </div>


  <div class="wrapper value-proposition">
     <div class="container-fluid">

      <div class="dog-rows">
        <div class="row">
          <div class="col-xs-12 col-md-offset-1 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/SadET", height: 350, width: 450, crop: :fit %> ');">
               <a class="card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-6">
            <!-- This div is centered and takes 4 columns -->
            <div class="home-item text-center">
              <p>Tired to see you're Dog Sad, when you're back home ...</p>
            </div>
          </div>
        </div>
      </div>

      <div class="dog-rows">
        <div class="row">
          <div class="col-xs-12 col-md-offset-1 col-md-6">
            <!-- This div is centered and takes 4 columns -->
            <div class="home-item text-center">
              <p>... or Mad at you</p>
            </div>
          </div>

          <div class="col-xs-12 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/Sad_Bouledog", height: 350, width: 450, crop: :fit %> ');">
                  <a class="card-link" href="#" ></a>
            </div>
          </div>
        </div>
      </div>

      <div class="dog-rows">
        <div class="row">
          <div class="col-xs-12 col-md-offset-1 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/DogsFaceTime", height: 350, width: 450, crop: :fit %> ');">
            <a class="card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-6">
            <!-- This div is centered and takes 4 columns -->
            <div class="home-item text-center">
              <p> Skyping with him could be an option :)...</p>
            </div>
          </div>
        </div>
      </div>

      <div class="dog-rows">
        <div class="row">
          <div class="col-xs-12 col-md-offset-1 col-md-6">
            <!-- This div is centered and takes 4 columns -->
            <div class="home-item text-center">
              <p>... And you dream to see him like this ...</p>
            </div>
          </div>

          <div class="col-xs-12 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/HappyDog", height: 350, width: 450, crop: :fit %> ');">
                  <a class="card-link" href="#" ></a>
            </div>
          </div>
        </div>
      </div>

      <div class="dog-rows message">
        <div class="row">
          <div class="col-xs-12 col-md-offset-2 col-md-8">
            <!-- This div is centered and takes 4 columns -->
            <div class="home-item slogan text-center">
              <p>We are here to help both of you</p>
            </div>
          </div>
        </div>
      </div>

      <div class="dog-rows">
        <div class="row">
          <div class="col-xs-12 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/dogs_handshake", height: 280, width: 350, crop: :fill %> ');">
              <a class="card-link" href="#" ></a>
            </div>
          </div>

          <div class="col-xs-12 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/Zenitude", height: 300, width: 400, crop: :fit %> ');">
              <a class="card-link" href="#" ></a>
            </div>
          </div>

          <div class="col-xs-12 col-md-4">
            <!-- This div is centered and takes 4 columns -->
            <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path "DogWalker/dog_girl", height: 300, width: 400, crop: :fit %> ');">
              <a class="card-link" href="#" ></a>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>


  <div class="wrapper-testimonials">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="testimonials">
              <div class="testimonials-title">
                <h2>Testimonials</h2>
              </div>
              <div class="testimonials-list">
                  <div class="testimonial-card">
                      <figure class="snip1192">
                        <blockquote>Andreia: I found finally peace of mind back when I'm at work, I know that my Molly will get some fresh air, and have a nice walk. </blockquote>
                        <div class="author">
                          <!-- <img src="http://res.cloudinary.com/pmarzagao/image/upload/v1527683260/8GaEWuxK_400x400.jpg"/> -->
                        <%= cl_image_tag "pg36t4mzhgbsghzeeq2w",width: 150, height: 150, crop: :thumb, gravity: :face %>
                        </div>
                  </div>
                  <div class="testimonial-card">
                      <figure class="snip1192">
                        <blockquote>Pedro: Now it's easier when coming back after a long day of work, I can enjoy my dog. He's much more quite and happy </blockquote>
                        <div class="author">
                        <%= cl_image_tag "qnscj3nhy31b9o1wiwxs",width: 150, height: 150, crop: :thumb, gravity: :face %>
                        </div>
                  </div>
                  <div class="testimonial-card">
                      <figure class="snip1192">
                        <blockquote>Jerôme: Don't need to be stressed anymore for Hatchi, I know his Dogwalker, it's a nice guy. Hatchi is between good hands, what a relief ... </blockquote>
                        <div class="author">
                           <%= cl_image_tag "gg7zpv1pkqydri0hwpjx",width: 150, height: 150, crop: :thumb, gravity: :face %>
                        </div>
                  </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Dogs", dogs_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Dogs", mydogs_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Walks", walks_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add a Dog", new_dog_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <!--   <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.picture,width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
 <!--      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to t(".sign_in", default: "Login / Sign Up"), new_user_session_path, class: "btn-loggin" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/walks/_form.html.erb
<%= simple_form_for [@dog, @walk] do |f| %>
  <%= f.input :startdate %>
  <%= f.input :startime %>
  <%#= f.input :photo %>
 <%#= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Take a walk", class: "btn btn-primary" %>
<% end %>

app/views/walks/index.html.erb
<h2>Hi dear Dogwalker, <%= current_user.firstname %></h2>
<% @walks.each do |walk| %>
  <p> Walk date: <%= walk.date_begin %></p>
  <p>at <%= walk.startime %></p>
  <p> Dog's name : <%= walk.dog.name %> </p>
  <p> Dog's breed: <%= walk.dog.breed %></p>
  <p> Dog owners name is : <%= walk.dog.user.firstname %> %></p>
<% end %>

app/views/walks/new.html.erb
<div class="container">
  <%= render 'form', walk: @walk %>
  <%= link_to 'back to Dogs', dogs_path  %>
</div>

app/views/walks/show.html.erb
<h2>Hi dear Dogwalker, <%= @walk.user.firstname %></h2>
<p> Walk date: <%= @walk.date_begin %></p>
<p>at <%= @walk.startime %></p>
<p> Dog's name : <%= @walk.dog.name %> </p>
<p> Dog's breed: <%= @walk.dog.breed %></p>
<p> Dog's owner name: <%= @walk.dog.user.firstname %></p>